--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Farmero14000/RankShop
build-by-default: true
branches:
- main
projects:
  RankShop:
    path: ""
    libs:
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^2.1.1
      - src: Farmero14/MoneySystem/MoneySystem
        version: ^1.0.0
    lint:
      phpstan: true
...
